build:
  image: armhfbuild/golang:1.5.3
  commands:
    - go get
    - go build
    - go test

notify:
  irc:
    prefix: build
    nick: depadrone
    channel: n0sec
    server:
      host: irc.freenode.net
      port: 6667

